# Generated by Django 5.2.5 on 2025-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('proceso', models.CharField(max_length=255)),
                ('mensaje', models.CharField(max_length=255)),
                ('datos', models.TextField()),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'db_table_comment': 'iLook - Paises para validar transacciones',
            },
        ),
    ]
