# Generated by Django 5.2.5 on 2025-10-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriavalidacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
