# Generated by Django 5.2.5 on 2025-10-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validar', '0002_alter_auditoriavalidacion_fecha'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='auditoriavalidacion',
            table_comment='iLook - Auditoria interna, archivos recibidos.',
        ),
        migrations.AddField(
            model_name='auditoriavalidacion',
            name='proceso_validacion',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
