# Generated by Django 5.2.5 on 2025-09-25 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tokenconvencimiento',
            index=models.Index(fields=['user'], name='sesion_toke_user_id_7ac8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenconvencimiento',
            index=models.Index(fields=['expires_at'], name='sesion_toke_expires_6a5f0d_idx'),
        ),
    ]
