# Generated by Django 5.2.5 on 2025-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_tokenconvencimiento_sesion_toke_user_id_7ac8a7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenconvencimiento',
            name='current_ip',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenconvencimiento',
            name='user_agent',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
