# Generated by Django 5.2.5 on 2025-10-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_tokenconvencimiento_current_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenconvencimiento',
            options={'ordering': ['-expires_at']},
        ),
    ]
