# Generated by Django 5.2.5 on 2025-09-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='contactopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estatus',
            field=models.CharField(choices=[('00', 'Activo'), ('01', 'Suspendido'), ('02', 'En registro'), ('98', 'Transferido'), ('99', 'Inactivo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='pacientes.paciente'),
        ),
    ]
