# Generated by Django 5.2.5 on 2025-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='estatus',
            field=models.CharField(choices=[('00', 'Activo'), ('01', 'Suspendido'), ('02', 'Vacaciones'), ('99', 'Desincorporado')], max_length=2),
        ),
    ]
