# Generated by Django 5.2.5 on 2025-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
