# Generated by Django 5.2.5 on 2025-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilr001',
            fields=[
                ('pk', models.CompositePrimaryKey('r001001', 'r001002', blank=True, editable=False, primary_key=True, serialize=False)),
                ('r001001', models.SmallIntegerField(verbose_name='Tabla')),
                ('r001002', models.CharField(max_length=15, verbose_name='Item')),
                ('r001003', models.CharField(max_length=150, verbose_name='Descripción')),
                ('r001004', models.CharField(max_length=1, verbose_name='Estatus')),
                ('r001005', models.CharField(max_length=50, verbose_name='Filler ALF')),
                ('r001006', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Filler NUM')),
                ('r001007', models.CharField(max_length=10, verbose_name='Usuario')),
                ('r001008', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table': 'ilr001',
                'db_table_comment': 'iLook - Tablas Generales',
                'managed': False,
            },
        ),
    ]
