# Generated by Django 5.2.5 on 2025-08-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ilr001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilr001',
            options={'managed': False, 'verbose_name': 'Tabla', 'verbose_name_plural': 'Tablas'},
        ),
    ]
