# Generated by Django 5.2.5 on 2025-08-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ilr001_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilr002',
            fields=[
                ('r002001', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('r002002', models.CharField(max_length=30, verbose_name='Descripción')),
                ('r002003', models.TimeField(verbose_name='Inicio')),
                ('r002004', models.TimeField(verbose_name='Fin')),
                ('r002005', models.CharField(max_length=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'ilr002',
                'managed': False,
            },
        ),
    ]
