# Generated by Django 5.2.5 on 2025-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ilr002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilm002',
            fields=[
                ('m002001', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código')),
                ('m002002', models.CharField(max_length=40, verbose_name='Descripción')),
                ('m002003', models.CharField(max_length=3, verbose_name='ISO')),
                ('m002004', models.CharField(max_length=15, verbose_name='Moneda contravalor')),
                ('m002005', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa actual')),
                ('m002006', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa anterior')),
                ('m002007', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa promedio')),
                ('m002008', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa generica')),
                ('m002009', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa generica anterior')),
                ('m002010', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Tasa generica promedio')),
                ('m002011', models.CharField(max_length=1, verbose_name='Estatus')),
                ('m002012', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m002013', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'ilm002',
                'db_table_comment': 'Tabla de monedas',
                'managed': False,
            },
        ),
    ]
