# Generated by Django 5.2.5 on 2025-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ilm002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilm003',
            fields=[
                ('m003001', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('m003002', models.CharField(max_length=40, verbose_name='Descripción')),
                ('m003003', models.CharField(max_length=2, verbose_name='Código Alfabetico ISO')),
                ('m003004', models.CharField(max_length=15, verbose_name='Moneda Oficial')),
                ('m003005', models.CharField(max_length=1, verbose_name='Estatus')),
                ('m003006', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m003007', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'ilm003',
                'db_table_comment': 'iLook - Paises',
                'managed': False,
            },
        ),
    ]
