# Generated by Django 5.2.5 on 2025-08-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ilm003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilm004',
            fields=[
                ('m004001', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('m004002', models.CharField(max_length=80, verbose_name='Descripción')),
                ('m004003', models.CharField(max_length=2, verbose_name='Gravedad')),
                ('m004004', models.CharField(max_length=2, verbose_name='Acción')),
                ('m004005', models.CharField(max_length=1, verbose_name='Estatus')),
                ('m004006', models.CharField(max_length=1, verbose_name='Clase')),
                ('m004007', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m004008', models.DateTimeField(auto_now=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'ilm004',
                'db_table_comment': 'iLook - Alertas',
                'managed': False,
            },
        ),
    ]
