# Generated by Django 5.2.5 on 2025-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ilm004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilm006',
            fields=[
                ('m006001', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False, verbose_name='Número')),
                ('m006002', models.CharField(max_length=100, verbose_name='Descripción')),
                ('m006003', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Prioridad')),
                ('m006004', models.CharField(blank=True, choices=[('  ', 'No validar'), ('RR', 'Operaciones financieras'), ('00', 'Canales')], max_length=2, verbose_name='Origen')),
                ('m006005', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='País')),
                ('m006007', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='Categoria Comercio')),
                ('m006009', models.CharField(blank=True, max_length=1, verbose_name='Instrumento')),
                ('m006011', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='BIN')),
                ('m006013', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='Canal')),
                ('m006015', models.CharField(blank=True, max_length=1, verbose_name='Terminal')),
                ('m006017', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='POS Entry mode')),
                ('m006019', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='alerta')),
                ('m006021', models.CharField(blank=True, choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='Código Transacción')),
                ('m006023', models.CharField(blank=True, choices=[(' ', 'No validar'), ('N', 'Natural'), ('J', 'Juridico'), ('G', 'Gobierno')], max_length=2, verbose_name='Tipo de Persona')),
                ('m006025', models.TimeField(blank=True, null=True, verbose_name='Hora desde')),
                ('m006026', models.TimeField(blank=True, null=True, verbose_name='Hora hasta')),
                ('m006028', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Lapso')),
                ('m006029', models.CharField(choices=[('S', 'Segundos'), ('M', 'Minutos'), ('H', 'Horas')], max_length=1, verbose_name='Unidad del lapso')),
                ('m006031', models.CharField(max_length=4, verbose_name='Codigo respuesta automática')),
                ('m006033', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Limite de transacciones')),
                ('m006035', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Monto limite por transacción')),
                ('m006037', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='Monto limite acumulado')),
                ('m006039', models.CharField(max_length=10, verbose_name='Código de la alerta')),
                ('m006040', models.CharField(max_length=1, verbose_name='Estatus')),
                ('m006041', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m006042', models.DateTimeField(verbose_name='Fecha')),
                ('m006043', models.CharField(choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='DE42')),
                ('m006044', models.CharField(max_length=3, verbose_name='DE48S42')),
                ('m006045', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='DE61S4')),
                ('m006046', models.CharField(blank=True, max_length=1, verbose_name='DE61S13')),
                ('m006047', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Puntos sensibiliad de riesgo')),
                ('m006048', models.CharField(max_length=6, verbose_name='Tipo operación contable')),
                ('m006049', models.CharField(choices=[(' ', 'No validar'), ('E', 'Modo entrada libre'), ('L', 'Listar')], max_length=1, verbose_name='Código transacción Web')),
                ('m006050', models.CharField(choices=[('F', 'Feriado'), ('H', 'Habil'), ('A', 'Ambos')], max_length=1, verbose_name='Feriado')),
                ('m006051', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='Primera Transacción')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'ilm006',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ilm027',
            fields=[
                ('pk', models.CompositePrimaryKey('m027001', 'm027002', blank=True, editable=False, primary_key=True, serialize=False)),
                ('m027001', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Código')),
                ('m027002', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Secuencia')),
                ('m027003', models.CharField(max_length=150, verbose_name='Descripción')),
                ('m027004', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Sensibilidad del riesgo')),
                ('m027005', models.CharField(max_length=1, verbose_name='Aprobado o rechazado')),
                ('m027006', models.CharField(max_length=1, verbose_name='Estatus')),
                ('m027007', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m027008', models.DateTimeField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'TransaccionConSensibilidad',
                'verbose_name_plural': 'TransaccionesConSensibilidad',
                'db_table': 'ilm027',
                'managed': False,
            },
        ),
    ]
