# Generated by Django 5.2.5 on 2025-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ilm006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenconvencimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
