# Generated by Django 5.2.5 on 2025-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ilm006_ilm027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilh003',
            fields=[
                ('h003001', models.DecimalField(decimal_places=0, max_digits=21, verbose_name='Código iLook')),
                ('h003002', models.CharField(max_length=15, verbose_name='Canal')),
                ('h003003', models.CharField(max_length=15, verbose_name='Moneda')),
                ('h003004', models.SmallIntegerField(verbose_name='Año')),
                ('h003005', models.SmallIntegerField(verbose_name='Mes')),
                ('h003006', models.SmallIntegerField(verbose_name='Dia')),
                ('h003007', models.TimeField(verbose_name='Hora')),
                ('h003008', models.CharField(max_length=10, verbose_name='Alerta')),
                ('h003009', models.CharField(max_length=1, verbose_name='Estatus')),
                ('h003010', models.CharField(max_length=10, verbose_name='Usuario')),
                ('h003011', models.DateTimeField(verbose_name='Fecha y Hora de Generac')),
                ('h003012', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Monto de la transaccion')),
                ('h003013', models.CharField(choices=[('D', 'DEBITO'), ('C', 'CREDITO')], max_length=1, verbose_name='Tipo (Debito o Credito)')),
                ('h003014', models.CharField(blank=True, max_length=500, verbose_name='Comentario del Operador')),
                ('h003015', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Hora_LK1')),
                ('h003016', models.CharField(choices=[('  ', 'No validar'), ('RR', 'Operaciones financieras'), ('00', 'Canales')], max_length=2, verbose_name='Origen')),
                ('h003017', models.CharField(max_length=1, verbose_name='Clase')),
                ('h003018', models.CharField(blank=True, max_length=10, verbose_name='Terminal')),
                ('h003019', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Evaluado')),
                ('h003020', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Promedio')),
                ('h003021', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Máximo')),
                ('h003022', models.CharField(max_length=10, verbose_name='Codigo Resultado')),
                ('h003023', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='LK1COD - COD DE TRANSACCION')),
                ('h003024', models.CharField(blank=True, max_length=23, verbose_name='LK1NOP - Nombre del POS')),
                ('h003025', models.DecimalField(blank=True, decimal_places=0, max_digits=2, verbose_name='LK1039 - Cod de respuesta')),
                ('h003026', models.CharField(blank=True, max_length=6, verbose_name='LK1DNO - Destino Nodo')),
                ('h003027', models.CharField(blank=True, max_length=6, verbose_name='LK1038 - No de Autorización')),
                ('h003028', models.CharField(blank=True, max_length=3, verbose_name='LK1022 - Entry Mode')),
                ('h003029', models.CharField(choices=[(' ', 'No validar'), ('N', 'Natural'), ('J', 'Juridico'), ('G', 'Gobierno')], max_length=1, verbose_name='LK1PER - PERSONA: N, J , G')),
                ('h003030', models.CharField(blank=True, max_length=10, verbose_name='Usuario / Analista Upd')),
                ('h003031', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Update')),
                ('h003032', models.IntegerField(verbose_name='Secuencia de operaciones')),
                ('h003033', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Codigo de Comercio')),
                ('h003034', models.CharField(choices=[('N', 'Nacional'), ('E', 'Extranjero')], max_length=1, verbose_name='Nacionalidad')),
                ('h003035', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Cedula o Rif')),
                ('h003036', models.CharField(blank=True, max_length=8, verbose_name='LK1041 - Campo 41 ')),
                ('h003037', models.CharField(blank=True, max_length=15, verbose_name='LK1MID - DE42 MERCHANT ID')),
                ('h003038', models.CharField(blank=True, max_length=3, verbose_name='LK1NRI - DE48s42 NIV RIESGO')),
                ('h003039', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='LK1PRE - DE61s4 TARJ PRESENT')),
                ('h003040', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='LK1PAP - DE61s13 POS COUNTRY')),
                ('h003041', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Limite de Sensibilidad en la Regla')),
                ('h003042', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Total Acumulado Sens. del Cliente')),
                ('h003043', models.DecimalField(decimal_places=0, max_digits=9)),
                ('h003044', models.CharField(max_length=6, verbose_name='TIPO OPERAC. CONTAB')),
                ('h003045', models.AutoField(primary_key=True, serialize=False, verbose_name='Indice ILH003 (Autogenerado)')),
                ('h003046', models.IntegerField(verbose_name='Indice ILH001')),
                ('h003047', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Anterior')),
                ('h003048', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='IA - Calculo Prediccion Numerico')),
                ('h003049', models.CharField(max_length=20, verbose_name='Clasificacion Riesgo IA')),
            ],
            options={
                'verbose_name': 'HistoricoAlerta',
                'verbose_name_plural': 'HistoricoAlertas',
                'db_table': 'ilh003',
                'db_table_comment': 'iLook - Historico de alertas',
                'managed': False,
            },
        ),
    ]
