# Generated by Django 5.2.5 on 2025-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tmptransaccioniso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de022',
            field=models.CharField(max_length=12, null=True, verbose_name='DE022 - Point of service entry mode'),
        ),
    ]
