# Generated by Django 5.2.5 on 2025-08-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tmptransaccioniso_de022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptransaccioniso',
            name='estatus',
            field=models.CharField(default=' ', max_length=1, verbose_name='Estatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmptransaccioniso',
            name='fecha_hora',
            field=models.DateTimeField(default='20250821T195200', verbose_name='Fecha-Hora de carga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmptransaccioniso',
            name='user',
            field=models.CharField(default='', max_length=20, verbose_name='Usuario de carga'),
            preserve_default=False,
        ),
    ]
