# Generated by Django 5.2.5 on 2025-08-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tmptransaccioniso_estatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmptransaccioniso',
            name='fecha_hora',
        ),
    ]
