# Generated by Django 5.2.5 on 2025-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_tmptransaccioniso_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de002',
            field=models.CharField(max_length=21, null=True, verbose_name='DE002 - PAN'),
        ),
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de003',
            field=models.CharField(max_length=6, null=True, verbose_name='DE003 - Processing Code'),
        ),
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de007',
            field=models.CharField(max_length=10, null=True, verbose_name='DE007 - Transmission date & time'),
        ),
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de018',
            field=models.CharField(max_length=4, null=True, verbose_name='DE018 - Merchant type, or merchant category code'),
        ),
        migrations.AlterField(
            model_name='tmptransaccioniso',
            name='de019',
            field=models.CharField(max_length=3, null=True, verbose_name='DE019 - Acquiring institution (country code)'),
        ),
    ]
