# Generated by Django 5.2.5 on 2025-08-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_tmptransaccioniso_de002_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptransaccioniso',
            name='proceso',
            field=models.IntegerField(default=0, verbose_name='Id Proceso de Validacion'),
            preserve_default=False,
        ),
    ]
