# Generated by Django 5.2.5 on 2025-09-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tmptransaccioniso_proceso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenConVencimiento',
        ),
    ]
