# Generated by Django 5.2.5 on 2025-10-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_tokenconvencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmptransaccioniso',
            options={'permissions': [('cargar_archivo_iso', 'Puede cargar archivo ISO'), ('ejecutar_validaciones_iso', 'Puede ejecutar validaciones ISO')], 'verbose_name': 'Transacción ISO', 'verbose_name_plural': 'Transacciones ISO'},
        ),
    ]
