# Generated by Django 5.2.5 on 2025-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tmptransaccioniso_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmp_transaccion_LK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lk1fec', models.DateTimeField(auto_now_add=True, verbose_name='Fecha-Hora de carga')),
                ('lk1act', models.DateTimeField(auto_now=True, verbose_name='Fecha-Hora de proceso')),
                ('lk1usu', models.CharField(max_length=20, verbose_name='Usuario carga')),
                ('lk1pro', models.IntegerField(verbose_name='Proceso de carga Id')),
                ('lk1est', models.CharField(choices=[('0', 'Pendiente por procesar'), ('1', 'En proceso'), ('2', 'Error'), ('4', 'Con alerta'), ('9', 'Procesado')], max_length=1, verbose_name='Estatus')),
                ('lk1hoy', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Fecha de transaccion SAAMMDD')),
                ('lk1hor', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Hora de transaccion HHMMSSxxx')),
                ('lk1ori', models.CharField(choices=[('  ', 'No validar'), ('RR', 'Operaciones financieras'), ('00', 'Canales')], max_length=2, verbose_name='Origen')),
                ('lk1cod', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Codigo de transaccion')),
                ('lk1tip', models.CharField(max_length=6, verbose_name='Tipo operacion contable')),
                ('lk1sbs', models.CharField(choices=[('D', 'DEBITO'), ('C', 'CREDITO')], max_length=1, verbose_name='Tipo de movimiento')),
                ('lk1cla', models.CharField(max_length=20, verbose_name='Numero de producto')),
                ('lk1nta', models.CharField(max_length=20, verbose_name='Numero de tarjeta')),
                ('lk1mon', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Monto de la transaccion')),
                ('lk1div', models.CharField(max_length=3, verbose_name='Divisa original de la transaccion')),
                ('lk1can', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Canal transaccional')),
                ('lk1ter', models.CharField(max_length=10, verbose_name='Terminal/POS/ATM')),
                ('lk1nop', models.CharField(max_length=23, verbose_name='Nombre del POS')),
                ('lk1ciu', models.CharField(max_length=14, verbose_name='Ciudad')),
                ('lk1pai', models.CharField(max_length=3, verbose_name='Pais origen')),
                ('lk1cat', models.CharField(max_length=4, verbose_name='Categoria del comercio')),
                ('lk1res', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Codigo respuesta')),
                ('lk1dno', models.CharField(max_length=6, verbose_name='Destino nodo')),
                ('lk1aut', models.CharField(max_length=6, verbose_name='Numero de autorizacion')),
                ('lk1pem', models.CharField(max_length=3, verbose_name='Modo de ingreso - 022 POS Entry mode')),
                ('lk1per', models.CharField(choices=[(' ', 'No validar'), ('N', 'Natural'), ('J', 'Juridico'), ('G', 'Gobierno')], max_length=1, verbose_name='Tipo de persona')),
                ('lk1nac', models.CharField(choices=[('V', 'Cedula'), ('P', 'Pasaporte'), ('R', 'RIF')], max_length=1, verbose_name='Tipo de documento Id')),
                ('lk1ced', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Numero de documento Id')),
                ('lk1cai', models.CharField(max_length=8, verbose_name='Identificacion del aceptante - 041 Card acceptor terminal identification')),
                ('lk1com', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Codigo del comercio')),
                ('lk1mid', models.CharField(max_length=15, verbose_name='Codigo del comercio emisor - DE42')),
                ('lk1nri', models.CharField(max_length=3, verbose_name='Nivel de riesgo - DE48s42')),
                ('lk1pre', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Tarjeta Presente - DE61s4')),
                ('lk1pap', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Pais emisor - DE61s13')),
                ('lk1cte', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='No definido')),
                ('lk1sat', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Saldo anterior')),
                ('lk1fil', models.CharField(max_length=21, verbose_name='Uso libre')),
            ],
            options={
                'verbose_name': 'TransaccionLK1',
                'verbose_name_plural': 'TransaccionesLK1',
                'db_table': 'tmp_transacciones_lk1',
                'db_table_comment': 'iLook - Carga movimiento formato LK1',
                'permissions': [('cargar_archivo_lk1', 'Puede cargar archivos LK1'), ('validar_archivo_lk1', 'Puede validar archivos LK1')],
            },
        ),
    ]
