# Generated by Django 5.2.5 on 2025-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tmp_transaccion_lk1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1cte',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='No definido'),
        ),
    ]
