# Generated by Django 5.2.5 on 2025-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_tmp_transaccion_lk1_lk1cte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_transaccion_lk1',
            name='lk1seq',
            field=models.IntegerField(default=0, verbose_name='Secuencia de carga por proceso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1aut',
            field=models.CharField(blank=True, max_length=6, verbose_name='Numero de autorizacion'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1cai',
            field=models.CharField(blank=True, max_length=8, verbose_name='Identificacion del aceptante - 041 Card acceptor terminal identification'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1cat',
            field=models.CharField(blank=True, max_length=4, verbose_name='Categoria del comercio'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1ciu',
            field=models.CharField(blank=True, max_length=14, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1cla',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de producto'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1div',
            field=models.CharField(blank=True, max_length=3, verbose_name='Divisa original de la transaccion'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1dno',
            field=models.CharField(blank=True, max_length=6, verbose_name='Destino nodo'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1fil',
            field=models.CharField(blank=True, max_length=21, verbose_name='Uso libre'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1mid',
            field=models.CharField(blank=True, max_length=15, verbose_name='Codigo del comercio emisor - DE42'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1nac',
            field=models.CharField(blank=True, choices=[('V', 'Cedula'), ('P', 'Pasaporte'), ('R', 'RIF')], max_length=1, verbose_name='Tipo de documento Id'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1nop',
            field=models.CharField(blank=True, max_length=23, verbose_name='Nombre del POS'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1nri',
            field=models.CharField(blank=True, max_length=3, verbose_name='Nivel de riesgo - DE48s42'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1nta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de tarjeta'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1ori',
            field=models.CharField(blank=True, choices=[('  ', 'No validar'), ('RR', 'Operaciones financieras'), ('00', 'Canales')], max_length=2, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1pai',
            field=models.CharField(blank=True, max_length=3, verbose_name='Pais origen'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1pem',
            field=models.CharField(blank=True, max_length=3, verbose_name='Modo de ingreso - 022 POS Entry mode'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1per',
            field=models.CharField(blank=True, choices=[(' ', 'No validar'), ('N', 'Natural'), ('J', 'Juridico'), ('G', 'Gobierno')], max_length=1, verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1sbs',
            field=models.CharField(blank=True, choices=[('D', 'DEBITO'), ('C', 'CREDITO')], max_length=1, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1ter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Terminal/POS/ATM'),
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1tip',
            field=models.CharField(blank=True, max_length=6, verbose_name='Tipo operacion contable'),
        ),
    ]
