# Generated by Django 5.2.5 on 2025-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tmp_transaccion_lk1_lk1seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1pro',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Proceso de carga Id'),
        ),
    ]
