# Generated by Django 5.2.5 on 2025-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tmp_transaccion_lk1_lk1pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmp_transaccion_lk1',
            name='lk1fid',
            field=models.CharField(db_index=True, default=' ', max_length=50, verbose_name='Identificador de carga Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmp_transaccion_lk1',
            name='lk1pro',
            field=models.IntegerField(verbose_name='Proceso de carga'),
        ),
    ]
