# Generated by Django 5.2.5 on 2025-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tmp_transaccion_lk1_lk1fid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilm016',
            fields=[
                ('pk', models.CompositePrimaryKey('m016001', 'm016002', blank=True, editable=False, primary_key=True, serialize=False)),
                ('m016001', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Numero de regla')),
                ('m016002', models.CharField(max_length=150, verbose_name='Descripcion Pais ISO')),
                ('m016003', models.CharField(max_length=15, verbose_name='Codigo Pais ISO')),
                ('m016004', models.SmallIntegerField()),
                ('m016005', models.CharField(max_length=10, verbose_name='Usuario')),
                ('m016006', models.DateTimeField(verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'ValidarPais',
                'verbose_name_plural': 'ValidarPaises',
                'db_table': 'ilm016',
                'db_table_comment': 'iLook - Paises para validar transacciones',
                'managed': False,
            },
        ),
    ]
