# Generated by Django 5.2.5 on 2025-10-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ilm016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilm016',
            options={'managed': False, 'verbose_name': 'ReglaPais', 'verbose_name_plural': 'ReglasPaises'},
        ),
    ]
