# Generated by Django 5.2.5 on 2025-10-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ilm016_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tmp_transaccion_lk1',
            unique_together={('lk1fid', 'lk1pro', 'lk1seq')},
        ),
    ]
