# Generated by Django 5.2.5 on 2025-09-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'EstiloLiterario',
                'verbose_name_plural': 'EstilosLiterarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='autor',
            name='estilos',
            field=models.ManyToManyField(related_name='autores', to='autor.estiloliterario'),
        ),
    ]
